##creating replicas using ReplicaSet for high availability, load balancing and self healing applications
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myfirstpod
  labels:
    app: flask

spec:
  template:
    metadata:
      name: myfirstpod
      labels:
        app: flask

    spec:
      containers:
        - name: myfirstpod
          image: akashkadao/python-git:v2.0.0

  replicas: 3
  selector:
    matchLabels:
      app: flask    
